### ISSUE TITLE
Custom element doesn't exist: aarlo_glance.

### ISSUE THREAD

**Issue by DadzBoyz** [twrecked/lovelace-hass-aarlo#16]
Good Evening.
I installed HACS without problem.
I seem to have installed aarlo through HACS without issue.
I followed instructions and installed Lovelace Hass Aarlo.

I've placed this at the top of my UI Config Editor:

resources:
  - url: /local/aarlo-glance.js
    type: module
  - url: /community_plugin/lovelace-hass-aarlo/hass-aarlo.js
    type: module

This starts at line 1,  before the entries for any Lovelace tabs/screens. 

When setting up the card, this is what is displayed in the card:

Custom element doesn't exist: aarlo_glance.
{
  "type": "custom:aarlo_glance",
  "entity": "camera.aarlo_front_door_camera",
  "name": "Front Door",
  "show": [
    "motion",
    "sound",
    "snapshot",
    "battery_level",
    "signal_strength",
    "captured_today",
    "image_date"
  ],
  "top_title": false,
  "top_status": false,
  "top_date": false,
  "image_click": "play"
}

Looking through my Hass install, there is no aarlo_glance.js anywhere.

Thanks for any help.

**Comment by twrecked** [comment]
`aarlo_glance.js` was the pre-HACS name. The manual install mechanism will create `local/aarlo_glance.js` for you but you don't need to do this. Also, the card is `aarlo-glance` not `aarlo_glance`. All this awkwardness is because this was originally part of `hass-arlo` source tree and I broke it out when I moved everything to HACS and I wanted to maintain some backwards compatibility.

So, to clarify, install the card through HACS and use this header:

```
resources:
  - type: module
    url: /community_plugin/lovelace-hass-aarlo/hass-aarlo.js
```

And use `custom:aarlo-glance` for the card type.

You might need to hit CTRL+R a few times to fully reload.

**Comment by lilfade** [comment]
@DadzBoyz Because i was a idiot, is your "entity": "camera.aarlo_front_door_camera", actually correct? Mine is named entity: camera.aarlo_front_yard so double check this line and should fix it up.

@twrecked maybe add this line to the docs with a asterisk for the idiots like me to ensure we don't just copy the "working" sample haha.

**Comment by twrecked** [comment]
Glad it's all working.

Document updated!

**Comment by DadzBoyz** [comment]
Thank You.


Dan Belcher
(813)966-9100
Dan@BelcherPros.com
[/var/folders/46/pzfsf7kd4kx7xh1pn_nd5skc0000gn/T/com.microsoft.Outlook/Content.MSO/AB327A36.tmp]<https://www.linkedin.com/in/danielbelcher/>
